In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("df_top5.csv")
df

C:\Users\fer_r\AppData\Local\Temp\ipykernel_25748\1333337711.py:1: DtypeWarning: Columns (9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("df_top5.csv")

,Country,League,home_team,away_team,home_score,away_score,season_year,first_half,second_half,home_team_goals_current_time,...,minuto_gol_home,minuto_gol_away,equipo_marco_primero,equipo_ganador,anoto_primero_y_gano,save_ratio_home,save_ratio_away,equipo_mas_faltas,mas_faltas_perdio,gana_quien_mas_amarillas
0,Germany,Bundesliga,B. Monchengladbach,Werder Bremen,4,1,2024/2025,3 - 0,1 - 1,"[""11'"", ""12'"", ""45'"", ""66'""]",...,11.0,75.0,home,home,1,0.800000,0.500000,home,0,False
1,Germany,Bundesliga,Freiburg,Mainz,0,0,2024/2025,0 - 0,0 - 0,NaN,...,NaN,NaN,ninguno,draw,0,1.000000,1.000000,away,1,False
2,Germany,Bundesliga,Dortmund,RB Leipzig,2,1,2024/2025,1 - 1,1 - 0,"[""30'"", ""65'""]",...,30.0,27.0,away,home,0,0.666667,0.714286,away,1,False
3,Germany,Bundesliga,Bayern Munich,Union Berlin,3,0,2024/2025,2 - 0,1 - 0,"[""15'"", ""43'"", ""51'""]",...,15.0,NaN,home,home,1,1.000000,0.571429,away,1,False
4,Germany,Bundesliga,Eintracht Frankfurt,Bochum,7,2,2024/2025,4 - 1,3 - 1,"[""9'"", ""18'"", ""20'"", ""32'"", ""61'"", ""66'"", ""69'""]",...,9.0,35.0,home,home,1,0.750000,0.222222,away,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34980,Spain,Laliga,Valladolid,Rayo Vallecano,1,3,2000/2001,1 - 1,0 - 2,NaN,...,NaN,NaN,ninguno,away,0,NaN,NaN,empate,0,False
34981,Spain,Laliga,Dep. La Coruna,Villarreal,4,2,2000/2001,2 - 0,2 - 2,NaN,...,NaN,NaN,ninguno,home,0,NaN,NaN,empate,0,False
34982,Spain,Laliga,Malaga,Celta Vigo,1,4,2000/2001,1 - 2,0 - 2,NaN,...,NaN,NaN,ninguno,away,0,NaN,NaN,empate,0,False
34983,Spain,Laliga,Real Madrid,Numancia,1,0,2000/2001,1 - 0,0 - 0,NaN,...,NaN,NaN,ninguno,home,0,NaN,NaN,empate,0,False
34984,Spain,Laliga,Valencia,Espanyol,0,1,2000/2001,0 - 0,0 - 1,NaN,...,NaN,NaN,ninguno,away,0,NaN,NaN,empate,0,False

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34985 entries, 0 to 34984
Data columns (total 60 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Country                               34985 non-null  object
 1   League                                34985 non-null  object
 2   home_team                             34985 non-null  object
 3   away_team                             34985 non-null  object
 4   home_score                            34985 non-null  int64
 5   away_score                            34985 non-null  int64
 6   season_year                           34985 non-null  object
 7   first_half                            34853 non-null  object
 8   second_half                           34875 non-null  object
 9   home_team_goals_current_time          15234 non-null  object
 10  home_team_goals                       13129 non-null  object
 11  home_team_goals_assist                13129 non-null  object
 12  away_team_goals_current_time          13089 non-null  object
 13  away_team_goals                       11508 non-null  object
 14  away_team_goals_assist                11508 non-null  object
 15  home_team_yellow_card_why             11078 non-null  object
 16  away_team_yellow_card_why             11617 non-null  object
 17  home_team_red_card_why                1075 non-null   object
 18  away_team_red_card_why                1255 non-null   object
 19  home_team_substitutions_current_time  15092 non-null  object
 20  home_team_substitutions               15091 non-null  object
 21  home_team_substitutions_with          15091 non-null  object
 22  away_team_substitutions_current_time  15089 non-null  object
 23  away_team_substitutions               15087 non-null  object
 24  away_team_substitutions_with          15087 non-null  object
 25  expected_goals_xg_home                2667 non-null   float64
 26  expected_goals_xg_away                2667 non-null   float64
 27  Ball_Possession_Home                  17407 non-null  float64
 28  Ball_Possession_Away                  17407 non-null  float64
 29  Shots_on_Goal_Home                    17407 non-null  float64
 30  Shots_on_Goal_Away                    17407 non-null  float64
 31  Offsides_Home                         34985 non-null  float64
 32  Offsides_Away                         34985 non-null  float64
 33  Goalkeeper_Saves_Home                 17407 non-null  float64
 34  Goalkeeper_Saves_Away                 17407 non-null  float64
 35  Fouls_Home                            34985 non-null  float64
 36  Fouls_Away                            34985 non-null  float64
 37  Red_Cards_Home                        34985 non-null  float64
 38  Red_Cards_Away                        34985 non-null  float64
 39  Yellow_Cards_Home                     34985 non-null  float64
 40  Yellow_Cards_Away                     34985 non-null  float64
 41  Total_Passes_Home                     7433 non-null   float64
 42  Total_Passes_Away                     7433 non-null   float64
 43  resultado                             34985 non-null  object
 44  diferencia_goles                      34985 non-null  int64
 45  total_goles                           34985 non-null  int64
 46  Mayor_Posesion                        17407 non-null  object
 47  equipo_mas_amarillas                  34985 non-null  object
 48  equipo_recibe_mas_tiros               34985 non-null  object
 49  portero_mas_paradas                   34985 non-null  object
 50  minuto_gol_home                       15222 non-null  float64
 51  minuto_gol_away                       13081 non-null  float64
 52  equipo_marco_primero                  34985 non-null  object
 53  equipo_ganador                        34985 non-null  object
 54  anoto_primero_y_gano                  34985 non-null  int64
 55  save_ratio_home                       16861 non-null  float64
 56  save_ratio_away                       17135 non-null  float64
 57  equipo_mas_faltas                     34985 non-null  object
 58  mas_faltas_perdio                     34985 non-null  int64
 59  gana_quien_mas_amarillas              34985 non-null  bool
dtypes: bool(1), float64(22), int64(6), object(31)
memory usage: 15.8+ MB

In [4]:
df.describe()

c:\Users\fer_r\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\fer_r\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,home_score,away_score,expected_goals_xg_home,expected_goals_xg_away,Ball_Possession_Home,Ball_Possession_Away,Shots_on_Goal_Home,Shots_on_Goal_Away,Offsides_Home,Offsides_Away,...,Total_Passes_Home,Total_Passes_Away,diferencia_goles,total_goles,minuto_gol_home,minuto_gol_away,anoto_primero_y_gano,save_ratio_home,save_ratio_away,mas_faltas_perdio
count,34985.000000,34985.000000,2667.000000,2667.000000,17407.000000,17407.000000,17407.000000,17407.000000,34985.000000,34985.000000,...,7433.000000,7433.000000,34985.000000,34985.00000,15222.000000,13081.000000,34985.000000,1.686100e+04,1.713500e+04,34985.000000
mean,1.538517,1.172274,1.588361,1.249516,51.115298,48.884874,4.976963,4.097662,1.016750,0.925825,...,462.931656,441.078030,1.346949,2.71079,28.068913,30.189206,0.385108,inf,inf,0.295012
std,1.287976,1.139893,0.908953,0.781945,10.689989,10.689999,2.728617,2.421370,1.569746,1.459752,...,139.237669,127.369141,1.202924,1.67011,23.480301,24.577206,0.486628,NaN,NaN,0.456055
min,0.000000,0.000000,0.000000,0.000000,18.000000,16.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,1.000000,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000
25%,1.000000,0.000000,0.910000,0.670000,44.000000,41.000000,3.000000,2.000000,0.000000,0.000000,...,367.000000,350.000000,0.000000,2.00000,8.000000,9.000000,0.000000,5.000000e-01,5.000000e-01,0.000000
50%,1.000000,1.000000,1.430000,1.120000,51.000000,49.000000,5.000000,4.000000,0.000000,0.000000,...,449.000000,428.000000,1.000000,3.00000,22.000000,24.000000,0.000000,7.142857e-01,6.666667e-01,0.000000
75%,2.000000,2.000000,2.140000,1.660000,59.000000,56.000000,7.000000,6.000000,2.000000,2.000000,...,547.000000,520.000000,2.000000,4.00000,43.000000,48.000000,1.000000,1.000000e+00,8.571429e-01,1.000000
max,9.000000,9.000000,7.200000,4.550000,84.000000,82.000000,22.000000,20.000000,12.000000,12.000000,...,3411.000000,975.000000,9.000000,11.00000,90.000000,90.000000,1.000000,inf,inf,1.000000

### Sacar medianas de Xg de cada equipos dependiendo su localia.

In [5]:
# Calcular medianas por equipo y localía
medianas_local = df.groupby('home_team')['expected_goals_xg_home'].median()
medianas_visitante = df.groupby('away_team')['expected_goals_xg_away'].median()

# Calcular mediana general solo si ambas columnas existen (para el mismo equipo)
# Ejemplo: Arsenal local + visitante → Arsenal general
df['all_xg_local'] = df['expected_goals_xg_home']
df['all_xg_visitante'] = df['expected_goals_xg_away']

general_local = df[['home_team', 'all_xg_local']].rename(columns={'home_team': 'team'}).groupby('team')['all_xg_local'].median()
general_visitante = df[['away_team', 'all_xg_visitante']].rename(columns={'away_team': 'team'}).groupby('team')['all_xg_visitante'].median()

# Función para rellenar home
def fill_xg_home(row):
    if pd.notnull(row['expected_goals_xg_home']):
        return row['expected_goals_xg_home']
    team = row['home_team']
    if team in medianas_local and not np.isnan(medianas_local[team]):
        return medianas_local[team]
    if team in general_local and not np.isnan(general_local[team]):
        return general_local[team]
    return df['expected_goals_xg_home'].median()

# Función para rellenar away
def fill_xg_away(row):
    if pd.notnull(row['expected_goals_xg_away']):
        return row['expected_goals_xg_away']
    team = row['away_team']
    if team in medianas_visitante and not np.isnan(medianas_visitante[team]):
        return medianas_visitante[team]
    if team in general_visitante and not np.isnan(general_visitante[team]):
        return general_visitante[team]
    return df['expected_goals_xg_away'].median()

# Aplicar funciones
df['expected_goals_xg_home'] = df.apply(fill_xg_home, axis=1)
df['expected_goals_xg_away'] = df.apply(fill_xg_away, axis=1)

# Limpiar columnas temporales
df.drop(columns=['all_xg_local', 'all_xg_visitante'], inplace=True)

### Sacar medianas de posesión de balon de cada equipos dependiendo su localia.

In [6]:
# 1️⃣ Calcular medianas por equipo local/visitante
medianas_pos_local = df.groupby('home_team')['Ball_Possession_Home'].median()
medianas_pos_visitante = df.groupby('away_team')['Ball_Possession_Away'].median()

# 2️⃣ Calcular mediana general del equipo (local + visitante)
df['all_pos_home'] = df['Ball_Possession_Home']
df['all_pos_away'] = df['Ball_Possession_Away']

general_pos_home = df[['home_team', 'all_pos_home']].rename(columns={'home_team': 'team'}).groupby('team')['all_pos_home'].median()
general_pos_away = df[['away_team', 'all_pos_away']].rename(columns={'away_team': 'team'}).groupby('team')['all_pos_away'].median()

# 3️⃣ Calcular mediana global solo para partidos local/visitante
global_pos_home = df['Ball_Possession_Home'].median()
global_pos_away = df['Ball_Possession_Away'].median()

# 4️⃣ Función para rellenar home
def fill_pos_home(row):
    if pd.notnull(row['Ball_Possession_Home']):
        return row['Ball_Possession_Home']
    team = row['home_team']
    if team in medianas_pos_local and not np.isnan(medianas_pos_local[team]):
        return medianas_pos_local[team]
    if team in general_pos_home and not np.isnan(general_pos_home[team]):
        return general_pos_home[team]
    return global_pos_home

# 5️⃣ Función para rellenar away
def fill_pos_away(row):
    if pd.notnull(row['Ball_Possession_Away']):
        return row['Ball_Possession_Away']
    team = row['away_team']
    if team in medianas_pos_visitante and not np.isnan(medianas_pos_visitante[team]):
        return medianas_pos_visitante[team]
    if team in general_pos_away and not np.isnan(general_pos_away[team]):
        return general_pos_away[team]
    return global_pos_away

# 6️⃣ Aplicar
df['Ball_Possession_Home'] = df.apply(fill_pos_home, axis=1)
df['Ball_Possession_Away'] = df.apply(fill_pos_away, axis=1)

# 7️⃣ Limpiar columnas temporales
df.drop(columns=['all_pos_home', 'all_pos_away'], inplace=True)

### Quitar nan de tiros a puerta.

In [7]:
# Contar NaNs (missing values)
nans_home = df['Shots_on_Goal_Home'].isna().sum()
nans_away = df['Shots_on_Goal_Away'].isna().sum()

# Contar ceros reales
zeros_home = (df['Shots_on_Goal_Home'] == 0).sum()
zeros_away = (df['Shots_on_Goal_Away'] == 0).sum()

# Mostrar resultados
print(f"Shots_on_Goal_Home → NaNs: {nans_home}, Ceros: {zeros_home}")
print(f"Shots_on_Goal_Away → NaNs: {nans_away}, Ceros: {zeros_away}")

Shots_on_Goal_Home → NaNs: 17578, Ceros: 273
Shots_on_Goal_Away → NaNs: 17578, Ceros: 550

In [8]:
# 1️⃣ Calcular medianas por equipo y localía
medianas_shots_local = df.groupby('home_team')['Shots_on_Goal_Home'].median()
medianas_shots_visitante = df.groupby('away_team')['Shots_on_Goal_Away'].median()

# 2️⃣ Calcular mediana general por equipo
df['all_shots'] = df[['Shots_on_Goal_Home', 'Shots_on_Goal_Away']].mean(axis=1)
medianas_shots_equipo = pd.concat([
    df[['home_team', 'all_shots']].rename(columns={'home_team': 'team'}),
    df[['away_team', 'all_shots']].rename(columns={'away_team': 'team'})
]).groupby('team')['all_shots'].median()

# 3️⃣ Función para rellenar Shots_on_Goal_Home
def fill_shots_home(row):
    if pd.notnull(row['Shots_on_Goal_Home']):
        return row['Shots_on_Goal_Home']
    team = row['home_team']
    if team in medianas_shots_local and not np.isnan(medianas_shots_local[team]):
        return medianas_shots_local[team]
    if team in medianas_shots_equipo and not np.isnan(medianas_shots_equipo[team]):
        return medianas_shots_equipo[team]
    return df['Shots_on_Goal_Home'].median()

# 4️⃣ Función para rellenar Shots_on_Goal_Away
def fill_shots_away(row):
    if pd.notnull(row['Shots_on_Goal_Away']):
        return row['Shots_on_Goal_Away']
    team = row['away_team']
    if team in medianas_shots_visitante and not np.isnan(medianas_shots_visitante[team]):
        return medianas_shots_visitante[team]
    if team in medianas_shots_equipo and not np.isnan(medianas_shots_equipo[team]):
        return medianas_shots_equipo[team]
    return df['Shots_on_Goal_Away'].median()

# 5️⃣ Aplicar funciones
df['Shots_on_Goal_Home'] = df.apply(fill_shots_home, axis=1)
df['Shots_on_Goal_Away'] = df.apply(fill_shots_away, axis=1)

# 6️⃣ Limpiar columna temporal
df.drop(columns=['all_shots'], inplace=True)

### Sacar paradas del portero.

In [9]:
# Paradas portero local (portero del home → calcula usando tiros del away)
df['Goalkeeper_Saves_Home'] = df.apply(
    lambda row: max(row['Shots_on_Goal_Away'] - row['away_score'], 0)
    if pd.isna(row['Goalkeeper_Saves_Home']) and 
       pd.notnull(row['Shots_on_Goal_Away']) and 
       pd.notnull(row['away_score'])
    else row['Goalkeeper_Saves_Home'],
    axis=1
)

# Paradas portero visitante (portero del away → calcula usando tiros del home)
df['Goalkeeper_Saves_Away'] = df.apply(
    lambda row: max(row['Shots_on_Goal_Home'] - row['home_score'], 0)
    if pd.isna(row['Goalkeeper_Saves_Away']) and 
       pd.notnull(row['Shots_on_Goal_Home']) and 
       pd.notnull(row['home_score'])
    else row['Goalkeeper_Saves_Away'],
    axis=1
)

In [10]:
# Paradas del portero
medianas_saves_local = df.groupby('home_team')['Goalkeeper_Saves_Home'].median()
medianas_saves_visitante = df.groupby('away_team')['Goalkeeper_Saves_Away'].median()

df['all_saves_home'] = df['Goalkeeper_Saves_Home']
df['all_saves_away'] = df['Goalkeeper_Saves_Away']

general_saves_home = df[['home_team', 'all_saves_home']].rename(columns={'home_team': 'team'}).groupby('team')['all_saves_home'].median()
general_saves_away = df[['away_team', 'all_saves_away']].rename(columns={'away_team': 'team'}).groupby('team')['all_saves_away'].median()

def fill_saves_home(row):
    if pd.notnull(row['Goalkeeper_Saves_Home']):
        return row['Goalkeeper_Saves_Home']
    team = row['home_team']
    if team in medianas_saves_local:
        return medianas_saves_local[team]
    if team in general_saves_home:
        return general_saves_home[team]
    return df['Goalkeeper_Saves_Home'].median()

def fill_saves_away(row):
    if pd.notnull(row['Goalkeeper_Saves_Away']):
        return row['Goalkeeper_Saves_Away']
    team = row['away_team']
    if team in medianas_saves_visitante:
        return medianas_saves_visitante[team]
    if team in general_saves_away:
        return general_saves_away[team]
    return df['Goalkeeper_Saves_Away'].median()

df['Goalkeeper_Saves_Home'] = df.apply(fill_saves_home, axis=1)
df['Goalkeeper_Saves_Away'] = df.apply(fill_saves_away, axis=1)
df.drop(columns=['all_saves_home', 'all_saves_away'], inplace=True)

###  Rellenar offsides con la mediana y localia

In [11]:
# 1️⃣ Calcular medianas
medianas_offsides_local = df.groupby('home_team')['Offsides_Home'].median()
medianas_offsides_visitante = df.groupby('away_team')['Offsides_Away'].median()

df['all_offsides_home'] = df['Offsides_Home']
df['all_offsides_away'] = df['Offsides_Away']

general_offsides_home = df[['home_team', 'all_offsides_home']].rename(columns={'home_team': 'team'}).groupby('team')['all_offsides_home'].median()
general_offsides_away = df[['away_team', 'all_offsides_away']].rename(columns={'away_team': 'team'}).groupby('team')['all_offsides_away'].median()

# 2️⃣ Funciones
def fill_offsides_home(row):
    if pd.notnull(row['Offsides_Home']):
        return row['Offsides_Home']
    team = row['home_team']
    if team in medianas_offsides_local:
        return medianas_offsides_local[team]
    if team in general_offsides_home:
        return general_offsides_home[team]
    return df['Offsides_Home'].median()

def fill_offsides_away(row):
    if pd.notnull(row['Offsides_Away']):
        return row['Offsides_Away']
    team = row['away_team']
    if team in medianas_offsides_visitante:
        return medianas_offsides_visitante[team]
    if team in general_offsides_away:
        return general_offsides_away[team]
    return df['Offsides_Away'].median()

# 3️⃣ Aplicar
df['Offsides_Home'] = df.apply(fill_offsides_home, axis=1)
df['Offsides_Away'] = df.apply(fill_offsides_away, axis=1)

# 4️⃣ Limpiar
df.drop(columns=['all_offsides_home', 'all_offsides_away'], inplace=True)

### Rellenar total de pases con mediana y localia

In [12]:
# 1️⃣ Calcular medianas
medianas_passes_local = df.groupby('home_team')['Total_Passes_Home'].median()
medianas_passes_visitante = df.groupby('away_team')['Total_Passes_Away'].median()

df['all_passes_home'] = df['Total_Passes_Home']
df['all_passes_away'] = df['Total_Passes_Away']

general_passes_home = df[['home_team', 'all_passes_home']].rename(columns={'home_team': 'team'}).groupby('team')['all_passes_home'].median()
general_passes_away = df[['away_team', 'all_passes_away']].rename(columns={'away_team': 'team'}).groupby('team')['all_passes_away'].median()

# 2️⃣ Funciones
def fill_passes_home(row):
    if pd.notnull(row['Total_Passes_Home']):
        return row['Total_Passes_Home']
    team = row['home_team']
    if team in medianas_passes_local:
        return medianas_passes_local[team]
    if team in general_passes_home:
        return general_passes_home[team]
    return df['Total_Passes_Home'].median()

def fill_passes_away(row):
    if pd.notnull(row['Total_Passes_Away']):
        return row['Total_Passes_Away']
    team = row['away_team']
    if team in medianas_passes_visitante:
        return medianas_passes_visitante[team]
    if team in general_passes_away:
        return general_passes_away[team]
    return df['Total_Passes_Away'].median()

# 3️⃣ Aplicar
df['Total_Passes_Home'] = df.apply(fill_passes_home, axis=1)
df['Total_Passes_Away'] = df.apply(fill_passes_away, axis=1)

# 4️⃣ Limpiar
df.drop(columns=['all_passes_home', 'all_passes_away'], inplace=True)

In [13]:
df

,Country,League,home_team,away_team,home_score,away_score,season_year,first_half,second_half,home_team_goals_current_time,...,minuto_gol_home,minuto_gol_away,equipo_marco_primero,equipo_ganador,anoto_primero_y_gano,save_ratio_home,save_ratio_away,equipo_mas_faltas,mas_faltas_perdio,gana_quien_mas_amarillas
0,Germany,Bundesliga,B. Monchengladbach,Werder Bremen,4,1,2024/2025,3 - 0,1 - 1,"[""11'"", ""12'"", ""45'"", ""66'""]",...,11.0,75.0,home,home,1,0.800000,0.500000,home,0,False
1,Germany,Bundesliga,Freiburg,Mainz,0,0,2024/2025,0 - 0,0 - 0,NaN,...,NaN,NaN,ninguno,draw,0,1.000000,1.000000,away,1,False
2,Germany,Bundesliga,Dortmund,RB Leipzig,2,1,2024/2025,1 - 1,1 - 0,"[""30'"", ""65'""]",...,30.0,27.0,away,home,0,0.666667,0.714286,away,1,False
3,Germany,Bundesliga,Bayern Munich,Union Berlin,3,0,2024/2025,2 - 0,1 - 0,"[""15'"", ""43'"", ""51'""]",...,15.0,NaN,home,home,1,1.000000,0.571429,away,1,False
4,Germany,Bundesliga,Eintracht Frankfurt,Bochum,7,2,2024/2025,4 - 1,3 - 1,"[""9'"", ""18'"", ""20'"", ""32'"", ""61'"", ""66'"", ""69'""]",...,9.0,35.0,home,home,1,0.750000,0.222222,away,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34980,Spain,Laliga,Valladolid,Rayo Vallecano,1,3,2000/2001,1 - 1,0 - 2,NaN,...,NaN,NaN,ninguno,away,0,NaN,NaN,empate,0,False
34981,Spain,Laliga,Dep. La Coruna,Villarreal,4,2,2000/2001,2 - 0,2 - 2,NaN,...,NaN,NaN,ninguno,home,0,NaN,NaN,empate,0,False
34982,Spain,Laliga,Malaga,Celta Vigo,1,4,2000/2001,1 - 2,0 - 2,NaN,...,NaN,NaN,ninguno,away,0,NaN,NaN,empate,0,False
34983,Spain,Laliga,Real Madrid,Numancia,1,0,2000/2001,1 - 0,0 - 0,NaN,...,NaN,NaN,ninguno,home,0,NaN,NaN,empate,0,False
34984,Spain,Laliga,Valencia,Espanyol,0,1,2000/2001,0 - 0,0 - 1,NaN,...,NaN,NaN,ninguno,away,0,NaN,NaN,empate,0,False

In [14]:
df.to_csv("df_top5.csv", index=False)

### Definir x e y

In [15]:
# Definir X, y
x = df[['Ball_Possession_Home', 'Ball_Possession_Away', 'Shots_on_Goal_Home', 'Shots_on_Goal_Away', 'Fouls_Home', 'Fouls_Away',
        'Yellow_Cards_Home', 'Yellow_Cards_Away', 'Red_Cards_Home', 'Red_Cards_Away', 'expected_goals_xg_home', 'expected_goals_xg_away',
        'Goalkeeper_Saves_Home', 'Goalkeeper_Saves_Away', 'Offsides_Home', 'Offsides_Away','Total_Passes_Home', 'Total_Passes_Away',
        'save_ratio_home', 'save_ratio_away']]

y = df['resultado']

# # Codificar target
# le = LabelEncoder()
# y_encoded = le.fit_transform(y)

# # Train Test Split
# x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)